apiVersion: v1
kind: Secret
metadata:
  name: sqs-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.AWS_SECRET_ACCESS_KEY | b64enc }}